#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# # The name of your application.
# APP_NAME=Mixpost
#
# # Key used to encrypt and decrypt sensitive data. Generate this using the following tool:
# # https://mixpost.app/tools/encryption-key-generator
# APP_KEY=
#
# # Debug mode setting. Set to `false` for production environments.
# APP_DEBUG=false
#
# # Your app's domain or subdomain, without the 'http://' or 'https://' prefix.
# APP_DOMAIN=example.com
#
# # Full application URL is automatically configured; no modification required.
# APP_URL=https://${APP_DOMAIN}
APP_NAME = data.get('APP_NAME', 'Mixpost')
APP_DEBUG = data.get('APP_DEBUG', 'false')
APP_DOMAIN = data.get('host')
APP_URL = f"https://{APP_DOMAIN}"

app_env = {
    'APP_NAME': APP_NAME,
    'APP_DEBUG': APP_DEBUG,
    'APP_DOMAIN': APP_DOMAIN,
    'APP_URL': APP_URL,
}
agent.write_envfile("mixpost-app.env", app_env)

# Make sure everything is saved inside the environment file
# just before starting systemd unit
#agent.dump_env()
